name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
      - 'app/**'
      - 'cmd/**'
 
permissions:
  contents: write
  packages: write

jobs:
  prepare-env:
    runs-on: tools
    outputs:
      DOCKERHUB_USERNAME: ${{ steps.load-env.outputs.username }}
      DOCKERHUB_PASSWORD: ${{ steps.load-env.outputs.password }}
    steps:
      - id: load-env
        run: |
          source /etc/profile.d/github.sh
          echo "username=$DOCKERHUB_USERNAME" >> $GITHUB_OUTPUT
          echo "password=$DOCKERHUB_PASSWORD" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare-env
    uses: shareit-solutions/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: ${{ github.repository }}
      dockerfile_path: ./Dockerfile
      context_path: .
      push_image: true
      dockerhub_username: ${{ needs.prepare-env.outputs.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ needs.prepare-env.outputs.DOCKERHUB_PASSWORD }}
    secrets: inherit

  # update based in branch
  update-image-tag:
    needs: build-and-push
    runs-on: tools
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Update image tag in Helm values
        run: |
          IMAGE_TAG=${{ needs.build-and-push.outputs.tag }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Updating production values file..."
            sed -i "s|tag: .*|tag: ${IMAGE_TAG}|g" ./charts/app/values-prd.yaml
          else
            echo "Updating staging values file..."
            sed -i "s|tag: .*|tag: ${IMAGE_TAG}|g" ./charts/app/values-stg.yaml
          fi
        
      - name: Commit and push updated values by branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./charts/app/values-stg.yaml ./charts/app/values-prd.yaml
          git commit -m "Update Docker image tag to ${IMAGE_TAG} [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git push origin HEAD:${GITHUB_REF_NAME}